use std::fs::{copy, create_dir, create_dir_all, write};
use std::path::Path;

use crate::lib_type::LibType;
use crate::{templating, Mode, PlistInfo, Result, Target};
use askama::Template;
use execute::command;

pub fn create_frameworks(
    targets: &[Target],
    lib_name: &str,
    generated_dir: &Path,
    mode: Mode,
    lib_type: LibType,
) -> Result<()> {
    for target in targets {
        create_framework(target, lib_name, generated_dir, mode, lib_type)?;
    }
    Ok(())
}

fn create_framework(
    target: &Target,
    lib_name: &str,
    generated_dir: &Path,
    mode: Mode,
    lib_type: LibType,
) -> Result<()> {
	println!("Creating framework for target: {:?}", target);
	println!("lib_name: {:?}", lib_name);
	println!("generated_dir: {:?}", generated_dir);
	println!("mode: {:?}", mode);
	println!("lib_type: {:?}", lib_type);

    let framework_dir = Path::new(generated_dir)
        .join(target.display_name())
        .join(format!("{}.framework", lib_name));

    println!("Creating framework at {}", framework_dir.display());

    create_dir_all(&framework_dir)?;

    copy_headers(&framework_dir, generated_dir)?;

    copy_module_map(&framework_dir, generated_dir)?;

    generate_plist_info(target, &framework_dir, lib_name)?;

	copy_binary(target, lib_name, &framework_dir, mode, lib_type)?;

    Ok(())
}

fn copy_headers(framework_dir: &Path, generated_dir: &Path) -> Result<()> {
    let header_path = framework_dir.join("Headers");
    create_dir(&header_path)?;

    for header in glob::glob(&format!("{}/*.h", generated_dir.display()))
        .map_err(|e: glob::PatternError| format!("Could not find header files: \n {e}"))?
    {
        let header =
            header.map_err(|e: glob::GlobError| format!("Could not find header file: \n {e}"))?;
        let file_name = header
            .file_name()
            .ok_or("Could not get file name")?
            .to_str()
            .ok_or("Could not convert file name to string")?
            .to_string();
        copy(header, &header_path.join(file_name))?;
    }
    Ok(())
}

// Copy module map and modify it to be a framework module
// The modulemap needs to be modified to be a framework module
fn copy_module_map(framework_dir: &Path, generated_dir: &Path) -> Result<()> {
    let module_path = framework_dir.join("Modules");
    create_dir(&module_path)?;

    let src_module_map_path = generated_dir.join("headers").join("module.modulemap");

    let target_module_map_path = module_path.join("module.modulemap");

    copy(src_module_map_path, &target_module_map_path)?;

    let sed_command = format!(
        "sed -i '' -e 's/^module /framework module /' {}",
        target_module_map_path.display()
    );
    command(sed_command)
        .spawn()?
        .wait_with_output()
        .map_err(|e| format!("Could not run sed command: \n {e}"))?;

    Ok(())
}

fn generate_plist_info(target: &Target, framework_dir: &Path, lib_name: &str) -> Result<()> {
    let plist_template = templating::FrameworkPlist {
        framework_name: lib_name,
        platforms: vec![target.platform().plist().platform_string],
    };

    write(
        &framework_dir.join("Info.plist"),
        plist_template.render().unwrap(),
    )
    .map_err(|e| format!("Could not write Info.plist: \n {e}"))?;

    Ok(())
}

// Framework name and binary name must be the same or xcodebuild -create-framework will fail with an error 70
// This presents issue with an earlier step targets.rs where the library name is used during rpath_install_id_commands
// The library name used is that generated by cargo build which as is will not work with frameworks.
// We need the name of the binary to be the same as the framework name which also has to be the same as the module name
// generated by uniffi
fn copy_binary(target: &Target, lib_name: &str, framework_dir: &Path, mode: Mode, lib_type: LibType) -> Result<()> {
	// library_file_name
	let lib_path = target.library_path(lib_name, mode, lib_type);
    copy(lib_path, &framework_dir.join(lib_name))?;

	Ok(())
}
// Layout
// YourFramework.framework/
// ├── Headers/
// │   ├── YourFramework.h
// │   └── OtherPublicHeaders.h
// ├── Modules/
// │   └── module.modulemap
// ├── YourFramework
// ├── Info.plist

// YourFramework.framework.dSYM/
// ├── Contents/
// 	├── Info.plist
// 	└── Resources/
// 		└── DWARF/
// 			└── YourFramework

// Module Map
// framework module YourFramework {
// 	umbrella header "YourFramework.h"
//
// 	export *
// 	module * { export * }
// }

// Info Plist according to ChatGPT. The template borrows from KMP
// <?xml version="1.0" encoding="UTF-8"?>
// <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
// <plist version="1.0">
// <dict>
// 	<key>CFBundleIdentifier</key>
// 	<string>com.example.YourFramework</string>
// 	<key>CFBundleVersion</key>
// 	<string>1.0</string>
// 	<key>CFBundleExecutable</key>
// 	<string>YourFramework</string>
// 	<key>CFBundleName</key>
// 	<string>YourFramework</string>
// 	<key>CFBundlePackageType</key>
// 	<string>FMWK</string>
// 	<key>CFBundleShortVersionString</key>
// 	<string>1.0</string>
// </dict>
// </plist>

// Create dsyms from compiled binary
// https://users.rust-lang.org/t/missing-dsym-on-macos-when-building-with-cargo/97543/7

// Create Universal binary using lipo ?
// Does this need to be the case for single slice dylib? I think yes but not 100% sure
// lipo -create -output YourFramework path/to/arm64/YourFramework path/to/x86_64/YourFramework

// Modify xcframework to include dylib
// xcodebuild -create-xcframework \
// -framework path/to/ios-arm64/YourFramework.framework \
// -debug-symbols path/to/ios-arm64/YourFramework.framework.dSYM \
// -framework path/to/ios-arm64_x86_64-simulator/YourFramework.framework \
// -debug-symbols path/to/ios-arm64_x86_64-simulator/YourFramework.framework.dSYM \
// -output YourFramework.xcframework

//source https://chat.shopify.io/share/21474da9-8fda-4d03-9bbd-96f7116d0955
